CREATE TABLE PILOTDIM (
PILOT_ID INT IDENTITY (1,1),
EMP_NUM INT,
EMP_FNAME VARCHAR(10),
EMP_LNAME VARCHAR(10)
)

CREATE TABLE AIRPLANEDIM (
AIRPLANE_ID INT IDENTITY(1,1),
MOD_CODE VARCHAR(10),
)


CREATE TABLE TIMEDIM (
TIME_ID INT IDENTITY(1,1),
CHAR_DATE DATETIME
)


CREATE TABLE FACTTABLE (
PILOT_ID INT,
AIRPLANE_ID INT,
TIME_ID INT,
REVENUE FLOAT(8),
FUEL_USED FLOAT(8),
DISTANCE FLOAT(8)
)

DROP TABLE PILOTDIM 
DROP TABLE AIRPLANEDIM
DROP TABLE TIMEDIM
DROP TABLE FACTTABLE


CREATE TABLE STAGING 
(
PILOT_ID INT,
EMP_NUM INT,
EMP_FNAME VARCHAR(10),
EMP_LNAME VARCHAR(10),
AIRPLANE_ID INT,
MOD_CODE VARCHAR(10),
TIME_ID INT,
CHAR_DATE DATETIME,
REVENUE FLOAT(8),
FUEL_USED FLOAT(8),
DISTANCE FLOAT(8)
)

DROP TABLE STAGING

ALTER TABLE PILOTDIM
ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (PILOT_ID)

ALTER TABLE AIRPLANEDIM
ADD CONSTRAINT PK_AIRPLANEDIM PRIMARY KEY (AIRPLANE_ID)

ALTER TABLE TIMEDIM
ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TIME_ID)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_PILOTDIM FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM(PILOT_ID)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_AIRPLANEDIM FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRPLANEDIM(AIRPLANE_ID)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM(TIME_ID)




