SELECT P.EMP_FNAME, P.EMP_LNAME
FROM PILOTDIM P INNER JOIN FACTTABLE F ON P.PILOT_ID = F.PILOT_ID
WHERE DISTANCE = (SELECT MAX(DISTANCE) FROM FACTTABLE)
GROUP BY P.EMP_FNAME, P.EMP_LNAME

SELECT A.MOD_CODE, MONTH(T.CHAR_DATE) AS [MONTH], SUM(F.REVENUE) AS [TOTAL REVENUE]
FROM  FACTTABLE F INNER JOIN AIRPLANEDIM A ON F.AIRPLANE_ID = A.AIRPLANE_ID
	  INNER JOIN TIMEDIM T ON F.TIME_ID = T.TIME_ID
GROUP BY A.MOD_CODE, MONTH(T.CHAR_DATE)
ORDER BY SUM(F.REVENUE) ASC

