CREATE PROCEDURE A10
AS
BEGIN


ALTER TABLE FACTTABLE
DROP CONSTRAINT FK_FACT_PILOTDIM 

ALTER TABLE FACTTABLE
DROP CONSTRAINT FK_FACT_AIRPLANEDIM 

ALTER TABLE FACTTABLE
DROP CONSTRAINT FK_FACT_TIMEDIM


TRUNCATE TABLE FACTTABLE
TRUNCATE TABLE PILOTDIM
TRUNCATE TABLE AIRPLANEDIM
TRUNCATE TABLE TIMEDIM

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_PILOTDIM FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM(PILOT_ID)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_AIRPLANEDIM FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRPLANEDIM(AIRPLANE_ID)

ALTER TABLE FACTTABLE
ADD CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM(TIME_ID)


INSERT INTO PILOTDIM (EMP_NUM, EMP_FNAME, EMP_LNAME) 
SELECT P.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME
FROM PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM

INSERT INTO AIRPLANEDIM (MOD_CODE)
SELECT MOD_CODE
FROM MODEL

INSERT INTO TIMEDIM (CHAR_DATE)
SELECT CHAR_DATE
FROM CHARTER

TRUNCATE TABLE STAGING 


INSERT INTO STAGING (EMP_NUM, EMP_FNAME, EMP_LNAME, MOD_CODE, CHAR_DATE, FUEL_USED, DISTANCE, REVENUE)
SELECT P.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, M.MOD_CODE, CH.CHAR_DATE, CH.CHAR_FUEL_GALLONS, CH.CHAR_DISTANCE, SUM(M.MOD_CHG_MILE*CH.CHAR_FUEL_GALLONS) AS REVENUE
FROM  PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM
	  INNER JOIN CREW C ON E.EMP_NUM = C.EMP_NUM
	  INNER JOIN CHARTER CH ON C.CHAR_TRIP = CH.CHAR_TRIP
	  INNER JOIN AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER
	  INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE  
GROUP BY P.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, M.MOD_CODE, CH.CHAR_DATE, MONTH(CH.CHAR_DATE), YEAR(CH.CHAR_DATE), CH.CHAR_FUEL_GALLONS, CH.CHAR_DISTANCE


UPDATE STAGING 
SET PILOT_ID = P.PILOT_ID
FROM STAGING S INNER JOIN PILOTDIM P ON S.EMP_NUM = P.EMP_NUM

UPDATE STAGING
SET AIRPLANE_ID = A.AIRPLANE_ID
FROM STAGING S INNER JOIN AIRPLANEDIM A ON S.MOD_CODE = A.MOD_CODE

UPDATE STAGING
SET TIME_ID = T.TIME_ID
FROM STAGING S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE

INSERT INTO FACTTABLE (PILOT_ID, AIRPLANE_ID, TIME_ID, FUEL_USED, DISTANCE, REVENUE)  
SELECT PILOT_ID, AIRPLANE_ID, TIME_ID, FUEL_USED, DISTANCE, REVENUE
FROM STAGING

END

EXEC A10

SELECT *
FROM STAGING

SELECT *
FROM FACTTABLE

 
